version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: abgitt/selenium-docker-flight:v-3
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - C:\Users\Abilash\Desktop\DockerMapper\search-results:/usr/share/abilash/test-output
  book-flight-module:
    image: abgitt/selenium-docker-flight:v-3
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - C:\Users\Abilash\Desktop\DockerMapper\book-flight-results:/usr/share/abilash/test-output
      