pipeline 
{
    agent any
    stages 
    {
        stage('Run Test') 
        {
            steps 
            {
                //sh
                bat "docker-compose up --no-color"
            }
        }
        stage('Bring it down') 
        {
            steps 
            {
                //sh
                bat "docker-compose down"
            }
        }
        
    }
}