pipeline 
{
    agent any
    stages 
    {
        stage('Start Grid') 
        {
            steps 
            {
                //sh      
                bat "docker-compose -f D:/DockerComposeFiles/GridAndTest/docker-compose.yaml up -d hub chrome firefox"
            }
        }
        stage('Run Test') 
        {
            steps 
            {
                //sh      
                bat "docker-compose -f D:/DockerComposeFiles/GridAndTest/docker-compose.yaml up search-module book-flight-module --no-color"
            }
        }
        stage('Stop Grid') 
        {
            steps 
            {
                //sh
                
                bat "docker-compose -f D:/DockerComposeFiles/GridAndTest/docker-compose.yaml down"
            }
        }
        
    }
}